name: Release LSP servers

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build ${{ matrix.crate }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        crate: [statix-ls, deadnix-ls]
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            cross: false
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
          - target: x86_64-apple-darwin
            os: macos-26-intel
            cross: false
          - target: aarch64-apple-darwin
            os: macos-26
            cross: false

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross
        if: matrix.cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build (native)
        if: "!matrix.cross"
        run: cargo build --release -p ${{ matrix.crate }} --target ${{ matrix.target }}

      - name: Build (cross)
        if: matrix.cross
        run: cross build --release -p ${{ matrix.crate }} --target ${{ matrix.target }}

      - name: Package
        run: |
          cd target/${{ matrix.target }}/release
          tar czf "${{ github.workspace }}/${{ matrix.crate }}-${{ matrix.target }}.tar.gz" ${{ matrix.crate }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate }}-${{ matrix.target }}
          path: ${{ matrix.crate }}-${{ matrix.target }}.tar.gz

  # FIXME: Doesn't work in forks :(
  # release:
  #   name: Create GitHub release
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         merge-multiple: true

  #     - name: Create release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         files: "*.tar.gz"
  #         generate_release_notes: true
